database:
  localuri: "mongodb://127.0.0.1:27017"
  remoteuri: "mongodb+srv://m001-student:m001-mongodb-basics@sandbox.pjdbh.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  databasename: travel_db
server:
  port: ":8084"
environment: 
  profile: "dev"