database:
  localuri: "mongodb://127.0.0.1:27017"
  remoteuri: "mongodb+srv://m001-student:m001-mongodb-basics@sandbox.pjdbh.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  databasename: travel_db
server:
  port: ":8084"
environment: 
  profile: "dev"
jwt:
  accesskey: "secret12isnot34"
  refreshkey: "oldsecretisactually12butnot34"
  issuer: "stlemmy_travel"